### ISSUE TITLE
Install scripts reference both port 5000 and 5001

### ISSUE THREAD

**Issue by sts10** [scidsg/blackbox#19]
I noticed there's still a handful of references to port `5000` in the install scripts. Wondering if we need to/should update those to `5001` now?

**Comment by glenn-sorrentino** [comment]
I was running into issues trying to run both the installer and app on port 5000, so used 5001. Maybe we can combine the two?

**Comment by sts10** [comment]
> I was running into issues trying to run both the installer and app on port 5000, so used 5001

Ah, this explains my confusion. I just wanted to make sure we had changed to `5001` in some places but had neglected to change in others. I now see that we need to use both! (And I don't know of any reason why that is bad...) Closing this!
